apiVersion: v1
kind: Namespace
metadata:
  name: APPLICATION_NAME
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: DEPLOYMENT_NAME
spec:
  interval: 5m0s
  path: ./_deploy/DEPLOYMENT_NAME/
  prune: true
  sourceRef:
    kind: GitRepository
    name: momentum
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: DEPLOYMENT_NAME-STAGE_NAME
spec:
  interval: 5m0s
  path: ./_deploy/DEPLOYMENT_NAME/
  prune: true
  sourceRef:
    kind: GitRepository
    name: momentum
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: DEPLOYMENT_NAME-STAGE_NAME-STAGE_NAME
spec:
  interval: 5m0s
  path: ./_deploy/DEPLOYMENT_NAME/
  prune: true
  sourceRef:
    kind: GitRepository
    name: momentum
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: APPLICATION_NAME-charts
  namespace: APPLICATION_NAME
spec:
  interval: 10m0s
  url: https://charts.bitnami.com/bitnami
