apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: 'APPLICATION_NAME'
spec:
  valuesFrom:
    - kind: ConfigMap
      name: base-values
    - kind: Secret
      name: base-secrets
    - kind: ConfigMap
      name: 'STAGE_NAME-values'
    - kind: Secret
      name: 'STAGE_NAME-secrets'
    - kind: ConfigMap
      name: 'STAGE_NAME-STAGE_NAME-values'
    - kind: Secret
      name: 'STAGE_NAME-STAGE_NAME-secrets'
    - kind: ConfigMap
      name: deploy-values
    - kind: Secret
      name: deploy-secrets
