apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../_base/
configMapGenerator:
- files:
  - values.yaml
  name: 'test-stage-values'
  options:
    disableNameSuffixHash: true
secretGenerator:
- files:
  - values.yaml=secrets.yaml
  name: 'test-stage-secrets'
  options:
    disableNameSuffixHash: true
patches:
  - path: release.yaml
labels:
- includeSelectors: true
  pairs:
    gitops.natron.io/application: 'test-app'
    gitops.natron.io/stage: 'test-stage'