apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 'DEPLOYMENT_NAME-STAGE_NAME-STAGE_NAME' # next stage would be 'DEPLOYMENT_NAME-STAGE_NAME--STAGE_NAME-{next_stage}'
spec:
  interval: 5m0s
  path: ./_deploy/DEPLOYMENT_NAME/
  prune: true
  sourceRef:
    kind: GitRepository
    name: momentum
