apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: test-app
spec:
  interval: '5m'
  chart:
    spec:
      version: 'v1.0.0'
      sourceRef:
        kind: HelmRepository
        name: 'test-app-charts'
        namespace: 'test-app'
  install:
    remediation:
      remediateLastFailure: true
  upgrade:
    remediation:
      remediateLastFailure: true
  valuesFrom:
    - kind: ConfigMap
      name: base-values
    - kind: Secret
      name: base-secrets
    - kind: ConfigMap
      name: deploy-values
    - kind: Secret
      name: deploy-secrets
