apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # @momentum: config
- ./ns.yaml
- ./repository.yaml
  # @momentum: deployments
- './DEPLOYMENT_NAME.yaml'
  # @momentum: stages
- ./STAGE_NAME/
