apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 'DEPLOYMENT_NAME-STAGE_NAME'
resources:
- ../../_base/
configMapGenerator:
- files:
  - values.yaml
  name: deploy-values
  options:
    disableNameSuffixHash: true
secretGenerator:
- files:
  - secrets.yaml
  name: deploy-secrets
  options:
    disableNameSuffixHash: true
labels:
- includeSelectors: true
  pairs:
    gitops.natron.io/stage: 'STAGE_NAME'
patches:
- path: release.yaml
